Import('env')

# Build unity
unity_lib = SConscript(
    dirs = 'unity',
    variant_dir = env.subst('$BUILD_DIR/unity'),
    duplicate = False,
    exports = {'env': env.Clone()},
)

Return('unity_lib')
